### ISSUE TITLE
Difference between MM-REACT and Visual ChatGPT

### ISSUE THREAD

**Issue by fengyuli-dev** [microsoft/MM-REACT#4]
Were these supposed to be technically separate projects? It seems they're tackling the same problem, although the idea is indeed amazing!

😄  So many people are working on prompting ChatGPT recently. 

It would be more exciting if there's some sort of benchmark, so we see quantitatively what our potentials are.

**Comment by mofahad** [comment]
@fengyuli-dev  totally agreed. What my insight are basically MM React is more towards extracting the text from images and performing receipt and invoice understanding . as couple of azure cognitive services like form recognizer endpoints are  used given below. While in the Visualchatgpt there only BLIP is used to understand the images. and for generation of images stable diffusion are there.  

(https://yourazureendpoint.cognitiveservices.azure.com/formrecognizer/)
