### ISSUE TITLE
When providing a url to the public demo the chat session is immediately ended

### ISSUE THREAD

**Issue by johncorring** [microsoft/MM-REACT#7]
Apparently this is a bug? 

When I provide a URL (https://live.staticflickr.com/7249/7739949104_9b6f522778_b.jpg, https://i.redd.it/vxecoy2vncqa1.jpg were tested) only a single response is provided, after which I am asked to "Please refresh and hit ‘Click to wake up MM-REACT’". When downloading the image and uploading as a file the session proceeds normally.

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/11300328/228030263-c13ddc9f-605d-4e46-bdce-d8644fc155ac.png">

**Comment by ffahmed** [comment]
Could you retry. If it cannot answer it should not break.

**Comment by johncorring** [comment]
Looks like it works now!
